const fs = require('fs');
const filePath = 'D:/AYAN/HRMS/js/auth/permissionService.js';
let content = fs.readFileSync(filePath, 'utf8');

const oldBlock = `    MANAGER: [
      'team.*',
      'team.view',
      'team.attendance',
      'team.leave',
      'team.approve',
      'people.view',
      'attendance.team',
      'attendance.view',
      'leave.view',
      'leave.approve',
      'approvals.*',
      'approvals.process',
      'performance.view',
      'requests.view',
      'workflows.view',
      'communication.view',
      'reports.view',
      'own.profile',
      'own.attendance',
      'own.leave',
      'own.documents',
      'own.requests',
      'own.expenses',
      'ess.view'
    ],

    TEAM_LEAD: [
      'team.view',
      'team.attendance',
      'team.leave',
      'attendance.team',
      'attendance.view',
      'leave.view',
      'performance.view',
      'requests.view',
      'workflows.view',
      'communication.view',
      'reports.view',
      'own.profile',
      'own.attendance',
      'own.leave',
      'own.documents',
      'own.requests',
      'ess.view'
    ],

    MENTOR: [
      'training.*',
      'training.view',
      'training.manage',
      'training.assess',
      'attendance.punch',
      'attendance.view',
      'leave.view',
      'leave.create',
      'documents.view',
      'communication.view',
      'performance.view',
      'own.profile',
      'own.attendance',
      'own.leave',
      'own.documents',
      'ess.view'
    ],`;

const newBlock = `    MANAGER: [
      'people.view',
      'team.*',
      'team.view',
      'team.attendance',
      'team.leave',
      'team.approve',
      'attendance.team',
      'attendance.view',
      'leave.view',
      'leave.approve',
      'approvals.*',
      'approvals.process',
      'performance.view',
      'requests.view',
      'workflows.view',
      'communication.view',
      'reports.view',
      'own.profile',
      'own.attendance',
      'own.leave',
      'own.documents',
      'own.requests',
      'own.expenses',
      'ess.view'
    ],

    OPERATIONS_MANAGER: [
      'people.view',
      'team.*',
      'team.view',
      'team.attendance',
      'team.leave',
      'team.approve',
      'attendance.team',
      'attendance.view',
      'leave.view',
      'leave.approve',
      'approvals.*',
      'approvals.process',
      'performance.view',
      'requests.view',
      'workflows.view',
      'communication.view',
      'reports.view',
      'own.profile',
      'own.attendance',
      'own.leave',
      'own.documents',
      'own.requests',
      'own.expenses',
      'ess.view'
    ],

    TEAM_LEAD: [
      'people.view',
      'team.view',
      'team.attendance',
      'team.leave',
      'attendance.team',
      'attendance.view',
      'leave.view',
      'performance.view',
      'requests.view',
      'workflows.view',
      'communication.view',
      'reports.view',
      'own.profile',
      'own.attendance',
      'own.leave',
      'own.documents',
      'own.requests',
      'ess.view'
    ],

    MENTOR_TRAINER: [
      'training.*',
      'training.view',
      'training.manage',
      'training.assess',
      'attendance.punch',
      'attendance.view',
      'leave.view',
      'leave.create',
      'documents.view',
      'communication.view',
      'performance.view',
      'own.profile',
      'own.attendance',
      'own.leave',
      'own.documents',
      'ess.view'
    ],`;

content = content.replace(oldBlock, newBlock);

fs.writeFileSync(filePath, content, 'utf8');
console.log('Patched permissionService.js role permissions');
